In [12]:
import numpy as np

def RELU(x):
    return np.maximum(0,x)

def relu_der(z):
    return 1.*(z>0)

def softmax(x):
    return np.exp(x)/np.sum(np.exp(x))

def softmax_der(x):
    prob = softmax(x)
#     print(np.shape(prob))
    r = np.matmul(prob.T, (np.ones_like(prob)-prob))
#     print(np.shape(r))
    return r

def oneHotEncode(y,softmaxClasses):
        yactual = np.matrix(np.zeros(softmaxClasses)).T
        yactual[y] = 1
        return yactual    
    
def crossEntropy(ypred,y,softmaxClasses):
    """Compute crossentropy from logits[batch,n_classes] and ids of correct answers"""
    #one hot encode
    yactual = oneHotEncode(y,softmaxClasses)
    l = np.log(ypred)
    return -np.sum(l*yactual)
#     logits_for_answers = logits[np.arange(len(logits)),reference_answers]
#     xentropy = - logits_for_answers + np.log(np.sum(np.exp(logits),axis=-1))
#     return xentropy
    

def delta_cross_entropy(y, X):
          m = y.shape[0]
          grad = softmax(X)
          idx = np.where(grad == y*grad)
          grad[idx] = grad[idx] - 1
          grad = grad/m
          return grad



class neuralNetwork():    
    FCreluLayers = 0  
    Weights = []
    Biases = []
    softmax = False
    softmaxClasses = 0
    loss = []
    delta = [[]];    dW = [[]];    db = [[]]
    act = []
    logits = []
    def FullyConnectedreluLayers(self, values):
        assert len(values) == self.FCreluLayers+1, "Number of fully connected layers are not the same."
        self.Weights.append([])
        self.Biases.append([])
        for i in range(1, self.FCreluLayers+1):            
            self.Weights.append(np.random.normal(0, 0.1, ([values[i-1], values[i]])))
            self.Biases.append(np.random.normal(0, 0.1, ([values[i], 1])))
            self.delta.append([]);    self.dW.append([]);    self.db.append([])
#             print(type(self.Weights[i]))   
    
    def softmaxLayer(self):
        previous = self.Weights[-1].shape[1]
        self.Weights.append(np.random.normal(0,0.1,[previous, self.softmaxClasses]))
        self.Biases.append(np.random.normal(0, 0.1, (self.softmaxClasses, 1)))
        self.delta.append([]);    self.dW.append([]);    self.db.append([])
        
    def calcLoss(ypred, yactual):
        if self.softmax == True:
            return crossEntropy(ypred,yactual, self.softmaxClasses)
    
    def feedForward(self,X):
#         a = []
        self.act.append(X.T)
#         l = self.FCLayers if softmax == False else self.FCLayers-1
        
        for i in range(1, self.FCreluLayers+1):
#             print(" weights shape: ", np.shape(self.Weights[i].T) , "a shape: ", np.shape(self.act[i-1]))
            self.logits.append(np.matmul(self.Weights[i].T, self.act[i-1]) + self.Biases[i])
            self.act.append( RELU(self.logits[-1]) )
            
#         print("-----")
        if self.softmax == True:
            self.logits.append(np.matmul(self.Weights[-1].T, self.act[-1]) + self.Biases[-1])
            self.act.append(softmax(self.logits[-1]))
#             print(np.sum(self.act[-1]))   
#             print(self.act[-1])
        return self.act[-1]
    
    def backprop(self, ypred, yact):
        L = 3       
        self.delta[L] = delta_cross_entropy(ypred,yact)
        print("delta: ", np.shape(self.delta[L]))
        self.db[L] = self.delta[L].copy()
        self.dW[L] = self.act[-1] * self.delta[L]
        print("dw shape: ", np.shape(self.dW[L]))
        asd = self.Weights[L] * self.delta[L].T
        print("W*Del shape: ", np.shape(asd))
        self.delta[L-1] = np.multiply(softmax_der(self.logits[L-1]), asd.T)
        print("new delta: ", np.shape(self.delta[L-1]))
        L -= 1        
#         self.delta[L] = delta_cross_entropy(ypred,yact)
        self.db[L] = self.delta[L].copy()
        self.dW[L] = self.act[L-1] * self.delta[L]
        print("dw shape: ", np.shape(self.dW[L]))
        bsd = np.matmul(self.Weights[L],self.delta[L].T)
        self.delta[L-1] = np.multiply(relu_der(self.logits[L-1]), bsd.T)
        print("new delta: ", np.shape(self.delta[L-1]))
        L -= 1        
#         self.delta[L] = delta_cross_entropy(ypred,yact)
        self.db[L] = self.delta[L].copy()
        self.dW[L] = self.act[L-1] * self.delta[L]
#         L -= 1
# #         print("shape delta:", delta[l].shape, " a shape: ", a[l-1].shape, "  dW shape: ", dW[l].shape)
#         if l > 1:
#             print("W[l] shape: ", W[l].shape)
#             delta[l-1] = np.multiply(actder(z[l-1]), W[l] * delta[l])
#         return a[-1]
#         return [np.shape(self.Weights[i]) for i in range(len(self.Weights))]
        for l in range(1,len(self.Weights)):            
            W[l] = W[l] - alpha * dW[l]
            b[l] = b[l] - alpha * db[l]


mnist = neuralNetwork()
mnist.__class__.FCreluLayers = 2 #exclusing the softmax
mnist.__class__.softmax = True
mnist.__class__.softmaxClasses = 10
N = 6
h1 = 32
h2 = 16
mnist.FullyConnectedreluLayers([N,h1,h2])
mnist.softmaxLayer()

ypred = mnist.feedForward( np.matrix([0,1,2,3,4,5]) )
# print(np.shape(ypred), np.zeros(10))
mnist.backprop(ypred, np.matrix(np.zeros(10)) )
# mnist.loss.append(mnist.calcLoss(ypred, yt))
# print(mnist.loss[-1])

# print([np.shape(mnist.Weights[i]) for i in range(len(mnist.Weights))])  
# print(mnist.feedForward(np.matrix([0,1,2,3,4,5]), 3 ))
# mnist.layerWeights[-1].shape[1]


delta:  (1, 10)
dw shape:  (10, 10)
W*Del shape:  (16, 1)
new delta:  (1, 16)
dw shape:  (32, 16)
new delta:  (16, 32)


ValueError: shapes (6,1) and (16,32) not aligned: 1 (dim 1) != 16 (dim 0)

In [199]:
# from sklearn.datasets import load_digits
# digits = load_digits()
# print("listing digits: ", list(digits))
# print("Number of samples: ", digits.data.shape[0])
# print("Size of each sample: ", digits.data.shape[1])
# print("Listing target names: ", list(digits.target_names))

# y = np.matrix(digits.target).T
# X = np.matrix(digits.data)
# print("Image at index 3: ")
# import matplotlib.pyplot as plt 
# plt.matshow(digits.images[3]) 
# plt.show()

In [106]:

# r = np.array([1,0,0])
# logits = np.array([0.6,0,0.5])
# logits_for_answers = logits[np.arange(len(logits)),r]

In [212]:
np.shape(np.matrix(np.zeros(5)).T)

(5, 1)

In [219]:
def oneHotEncode(y,softmaxClasses):
        yactual = np.matrix(np.zeros(softmaxClasses)).T
        yactual[y] = 1
        return yactual
    
def crossEntropy(ypred,y,softmaxClasses):
    """Compute crossentropy from logits[batch,n_classes] and ids of correct answers"""
    #one hot encode
    yactual = oneHotEncode(y,softmaxClasses)
    print(yactual)
    l = np.log(ypred)
    print(l)
    return - np.sum(l*yactual)/yactual.shape[0]

crossEntropy(np.array([1.6,3.4,1.4,4]), 2, 4)

[[0.]
 [0.]
 [1.]
 [0.]]
[0.47000363 1.22377543 0.33647224 1.38629436]


-0.08411805915530322

In [221]:
def delta_cross_entropy(y, X):
          m = y.shape[0]
          grad = softmax(X)
          idx = np.where(grad == y*grad)
          grad[idx] = grad[idx] - 1
          grad = grad/m
          return grad
delta_cross_entropy(np.array([4,3,2,1]), np.array([3,4,12,4]))

array([ 3.08279633e-05,  8.37990924e-05,  2.49801574e-01, -2.49916201e-01])